### ISSUE TITLE
Could you pls give me some clues on the hyperparameters for ImageNet training?

### ISSUE THREAD

**Issue by iamweiweishi** [LiyuanLucasLiu/RAdam#11]
Hi, thank you for you great contribution. 
And I have tried some hyperparameters for Imagenet training by rAdam, but the acc never surpassed 0.32.
Could you pls send me some key params, like 'lr' 'beta1' 'beta2' 'schedule' 'gamma' 'weight_decay'.
Thank you.

**Comment by LiyuanLucasLiu** [comment]
Thanks for asking : -) I added some recipes to: https://github.com/LiyuanLucasLiu/RAdam/blob/master/cifar_imagenet/recipes.md#imagenet
