### ISSUE TITLE
Different implementation of radam.py 

### ISSUE THREAD

**Issue by tanaka-jp** [LiyuanLucasLiu/RAdam#19]
The implementation of RAdam is different between these two files.
  1. RAdam/radam.py
  2. RAdam/language-model/model_word_ada/radam.py

Which should I use ?

And there is a parameter (self.buffer) in the first file.
What is the role of this ?

**Comment by LiyuanLucasLiu** [comment]
Please use `RAdam/radam.py`. These two implementations are essentially the same -- the buffer is  used to speed up (i.e., for parameters with the same `step`, we do not need to recalculate all the `** step`). These two implementations are based on the different buffer implementations (the second assume all parameters have the same `step`, which is true for that specific project).
