### ISSUE TITLE
Speed performance

### ISSUE THREAD

**Issue by ivanvovk** [LiyuanLucasLiu/RAdam#21]
Good day! Thanks for your work.

Is RAdam more computationally effective than Adam? In my task setting RAdam makes much faster steps on the same batches and I'm trying to figure out why...
![image](https://user-images.githubusercontent.com/17574560/63419056-c6794a00-c40c-11e9-9811-d892a9aea1c1.png)

**Comment by LiyuanLucasLiu** [comment]
I think the reason is the cache mechanism used in `RAdam`. My guess is `PlainRAdam` is slower than the vanilla `Adam`, and `RAdam` is faster than them.

**Comment by ivanvovk** [comment]
Thanks for your reply. I suppose I've catched the problem. There is smth wrong with GPU where training with Adam was situated. I don't think Adam makes steps so slower than RAdam. The latter might be a bit faster, but not so much as I experienced. Nonetheless, it'll be great if somebody will make fair computational cost comparison of these optimizers one day.

**Comment by LiyuanLucasLiu** [comment]
Yes, agree. Typically, I think RAdam has almost the same speed with Adam, while the PlainRAdam is really slow...

**Comment by sholderbach** [comment]
@LiyuanLucasLiu Just as a question regarding your optimizations in `RAdam`, what is the reasoning behind the buffer with size 10? Wouldn't it be sufficient to cache computations just for one step count?

**Comment by LiyuanLucasLiu** [comment]
10 is just a random number, in case some parameters will have different `steps`.
