### ISSUE TITLE
Does RAdam break training with different learning rates for different param_groups?

### ISSUE THREAD

**Issue by sholderbach** [LiyuanLucasLiu/RAdam#24]
If I understand the source code for `RAdam` in `radam.py` correctly the global buffer will cache `step_size` parameters just depending on the `state['step']`. This would fail in training regimes where each `param_group` has its own learning rate as the buffer would contain a `step_size` based on the learning rate from the first processed `group`.

**Comment by sholderbach** [comment]
I did a few experiments and they confirm that the training looks like it always uses the learning rate of the first parameter group.

See the corresponding notebook at [https://nbviewer.jupyter.org/gist/sholderbach/a92e15fe8588d62f1804e9b2c508f0ce](https://nbviewer.jupyter.org/gist/sholderbach/a92e15fe8588d62f1804e9b2c508f0ce)

**Comment by LiyuanLucasLiu** [comment]
Nice catch : -) Thanks for bringing this up. Just fixed in the latest version by removing `lr` out of buffer.

**Comment by sholderbach** [comment]
Wow that was a quick fix!
Thank you very much.
