### ISSUE TITLE
 adam-2k

### ISSUE THREAD

**Issue by huoxuelu** [LiyuanLucasLiu/RAdam#25]
Could you explain how adam-2k is designed to get additional samples, thank you

**Comment by LiyuanLucasLiu** [comment]
The following command is for reproduce the adam-2k experiment (as in the [recipe](https://github.com/LiyuanLucasLiu/RAdam/blob/master/nmt/recipes.md)):
```
CUDA_VISIBLE_DEVICES=0 fairseq-train data-bin/iwslt14.tokenized.de-en -a transformer_iwslt_de_en --optimizer adam2 --lr 0.0003086 -s de -t en --label-smoothing 0.1 --dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler linear --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --max-update 72000 --warmup-updates 1 --adam-betas '(0.9, 0.999)' --save-dir /cps/gadam/nmt/adam_1k --tb-tag adam_1k --user-dir ./my_module --fp16 --restore-file x.pt --adam-freeze 2000
```
In [adam2.py](https://github.com/LiyuanLucasLiu/RAdam/blob/master/nmt/my_module/adam2.py), the first 2000 updates will only update `exp_avg_sq`.
