### ISSUE TITLE
Does RAdam have a Keras version？

### ISSUE THREAD

**Issue by xingyi-li** [LiyuanLucasLiu/RAdam#3]
Hi,  good job! 
You implemented RAdam in PyTorch version,  is it possible to offer a Keras version later? 
Appreciate :) 
你好，你是用PyTorch实现的RAdam，那么有没有计划提供一个Keras版本的RAdam呢？多谢啦

**Comment by aquadzn** [comment]
> Hi, good job!
> You implemented RAdam in PyTorch version, is it possible to offer a Keras version later?
> Appreciate :)
> 你好，你是用PyTorch实现的RAdam，那么有没有计划提供一个Keras版本的RAdam呢？多谢啦

https://github.com/CyberZHG/keras-radam
somebody just did lol

**Comment by sangenan** [comment]
someone could offer a Tensorflow version

**Comment by xingyi-li** [comment]
@aquadzn Thanks for your kind reminder, I will have a try on that one :)

**Comment by sayakpaul** [comment]
Here's another one: https://github.com/titu1994/keras_rectified_adam?files=1

Works with `tesnorflow 1.12+` and `keras 2.2.4+`.

**Comment by preachermaan** [comment]
@singngai make the switch to PyTorch! You won't regret it!

**Comment by xingyi-li** [comment]
@safekidda You're absolutely right, thanks for your advice, but we have adopted Keras as our software framework for our program this time. I will make the switch to PyTorch next time. Really appreciate your suggestion.

**Comment by xingyi-li** [comment]
@sayakpaul Really appreciate, I will definitely have a try on it, thanks!

**Comment by LiyuanLucasLiu** [comment]
Thanks for bringing this up & all implementations : -) If you find anything worth sharing, feel free to submit a PR.
