### ISSUE TITLE
Having issues importing to a Kaggle notebook

### ISSUE THREAD

**Issue by spencerkraisler** [LiyuanLucasLiu/RAdam#31]
Hello,

I tried importing RAdam in a Kaggle notebook. The usual way to import GitHub repos in Kaggle notebooks is to write 

```
!pip install git+https://github.com/LiyuanLucasLiu/RAdam
from radam import RAdam
```

However, after running I got this error:

> Collecting git+https://github.com/LiyuanLucasLiu/RAdam
>   Cloning https://github.com/LiyuanLucasLiu/RAdam to /tmp/pip-req-build-flm052t0
>   Running command git clone -q https://github.com/LiyuanLucasLiu/RAdam /tmp/pip-req-build-flm052t0
>     ERROR: Command errored out with exit status 1:
>      command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-flm052t0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-flm052t0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
>          cwd: /tmp/pip-req-build-flm052t0/
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/opt/conda/lib/python3.6/tokenize.py", line 452, in open
>         buffer = _builtin_open(filename, 'rb')
>     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-flm052t0/setup.py'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Any ideas?
Thank you.

**Comment by LiyuanLucasLiu** [comment]
Yes, this is not wrapped as a python package (thus cannot be installed via pip). Feel free to just copy and paste the code into your project.
