### ISSUE TITLE
What's the difference between RAdam and PlainRAdam?

### ISSUE THREAD

**Issue by seraphzl** [LiyuanLucasLiu/RAdam#48]
Hi,

There are RAdam and PlainRAdam in the src file (see https://github.com/LiyuanLucasLiu/RAdam/blob/master/radam/radam.py).
What's the difference between them, and which one should I use?

**Comment by LiyuanLucasLiu** [comment]
Hi, thanks for asking. Both of them work and `RAdam` should be faster. As to their difference, `RAdam` is the optimized version -- it caches the value of the rectification term to avoid overheads, while `PlainRAdam` is the exact implementation.
