### ISSUE TITLE
Algorithm 2 Arxiv paper 1/beta2 typo?

### ISSUE THREAD

**Issue by danielhanchen** [LiyuanLucasLiu/RAdam#55]
Hey again!

Not 100% sure, in v1 of your paper, beta2 was used.
In v2 and v3, 1/beta2 is used.

So is 1/beta2 correct?
![image](https://user-images.githubusercontent.com/23090290/95043257-05a94e00-0728-11eb-9865-30c7bfa8900e.png)

**Comment by LiyuanLucasLiu** [comment]
nice catch, i'll update the paper to fix this.

**Comment by danielhanchen** [comment]
Cool!
