### ISSUE TITLE
Why there are 10 slots in the buffer?

### ISSUE THREAD

**Issue by nihil-admirari** [LiyuanLucasLiu/RAdam#56]
Hi.

I'm trying to understand RAdam implementation:
```py
defaults = dict(..., buffer=[[None, None, None] for _ in range(10)])
...
for group in self.param_groups:
    for p in group['params']:
        ...
        state = self.state[p]
        ...
        state['step'] += 1
        buffered = group['buffer'][int(state['step'] % 10)]
        if state['step'] == buffered[0]:
            ...  # Reuse rectification constants computed during handling of a previous param.
        else:
            ...  # Compute rectification constants for a new step.
```
To me, it looks like `state['step']` is steadily incremented by one, and only the values for a previous step can possibly be reused, so a buffer with a capacity of one would be sufficient. But the actual buffer has 10 entries. What for?

**Comment by LiyuanLucasLiu** [comment]
Thanks for asking : -)

In some applications, some parameters may be fixed in some epoches (e.g., pre-training). I feel buffering ten entries costs almost nothing (comparing to one), but is more flexible in some corner cases.
