### ISSUE TITLE
Any concern for using `math.sqrt` instead of `torch.sqrt`

### ISSUE THREAD

**Issue by wenmin-wu** [LiyuanLucasLiu/RAdam#57]
I find you use a lot of `math.sqrt` in your [implementation](https://github.com/LiyuanLucasLiu/RAdam/blob/master/radam/radam.py#L74). Any concern for not using `torch.sqrt` instead? I think `math.sqrt` is slower than `torch.sqrt` because it's on CPU.

**Comment by LiyuanLucasLiu** [comment]
I believe since those computations take float numbers as inputs (instead of tensor), it should not be a problem.

**Comment by wenmin-wu** [comment]
Got it, thanks
