### ISSUE TITLE
Deprecated Warning in `RAdam` with torch==1.7.1

### ISSUE THREAD

**Issue by wenmin-wu** [LiyuanLucasLiu/RAdam#58]
Hi  @LiyuanLucasLiu , thanks for your incredible lib. With `RAdam` I got better performance without changing any hyperparameter. However, this a deprecated warning in `RAdam` with `torch==1.7.1`:
```
UserWarning: This overload of addcmul_ is deprecated:
	addcmul_(Number value, Tensor tensor1, Tensor tensor2)
Consider using one of the following signatures instead:
	addcmul_(Tensor tensor1, Tensor tensor2, *, Number value) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
```

according to the doc of `addcmul_` in `torch==1.7.1`
```
Docstring:
addcmul_(tensor1, tensor2, *, value=1) -> Tensor

In-place version of :meth:`~Tensor.addcmul`
Type:      builtin_function_or_method
```
so to adapt to 1.7.1 and disable this warning, I only need to change `exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)` to `exp_avg_sq.mul_(beta2).addcmul_(grad, grad, 1 - beta2)`, right?

**Comment by LiyuanLucasLiu** [comment]
Yes, there is a PR you can refer to: #51

**Comment by LiyuanLucasLiu** [comment]
BTW, glad you enjoy the paper (performance improvment is indeed a sideproduct of our study) and thanks for letting me know : -)
