### ISSUE TITLE
Should one be using RAdam or PlainRadam?

### ISSUE THREAD

**Issue by brando90** [LiyuanLucasLiu/RAdam#65]
Perhaps a small tutorial of how to use the code in practice might be useful?

**Comment by LiyuanLucasLiu** [comment]
```RAdam``` and ```PlainRAdam``` are essentially the same. ```RAdam``` is an optimized version (with using a buffer) and should run faster, ```PlainRAdam``` is provided as a reference to better understand the implementation of ```RAdam```.
