### ISSUE TITLE
Does RAdam usually need an annealing and warm up scheduler?

### ISSUE THREAD

**Issue by brando90** [LiyuanLucasLiu/RAdam#68]
since it fixes the variance issue wouldn't it mean it still needs a annealing scheduler (but not a warm up scheduler)?

**Comment by brucewlee** [comment]
I'm also interested

**Comment by LiyuanLucasLiu** [comment]
Thanks for asking and sorry that I just noticed this issue. 

In most cases, RAdam needs an annealing scheduler. 

If the original scheduler is annealing with warmup, it would make your life easier to use the same scheduler as changing the scheduler usually requires you to re-tune hyper-parameters. In my experience, adding more warmup is usually harmless (except in cases like small datasets), and using insufficient warmup can cause serious troubles.
