### ISSUE TITLE
Question regarding 2nd Moment Update

### ISSUE THREAD

**Issue by thisisbowen** [LiyuanLucasLiu/RAdam#69]
Hi Lucas,

First of all I would like to say thank you as the RAdam is really an amazing optimizer I have been using since last year. 

Recently I am interested in the algorithm behind RAdam and I have a dumb question if you don't mind - the update of exponential moving 2nd moment formula in your paper is: v<sub>t</sub> ← 1/β<sub>2</sub>v<sub>t-1</sub> + (1 - β<sub>2</sub>)g<sub>t</sub><sup>2</sup>. I remembered in Adam optimizer, the update of is v<sub>t</sub> ← β<sub>2</sub>v<sub>t-1</sub> + (1 - β<sub>2</sub>)g<sub>t</sub><sup>2</sup> without "1/". I also noticed that in your paper's version 1 the formula does not include "1/", so why is "1/" added?

I also checked the code, if I understand correctly, [the following](https://github.com/LiyuanLucasLiu/RAdam/blob/master/radam/radam.py#L58) is updating the 2nd moment:
```
exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
```
Could kindly help me out when you have free time?

Many thanks,
Bowen

**Comment by LiyuanLucasLiu** [comment]
Thanks for reaching out! It is really an encouragement to hear you like our work!

As to the second momentum update, it is indeed a typo and should be β_2 instead of 1 / β_2. I will update the paper in the next version. 

Best,
Liyuan
